### ISSUE TITLE
Make it possible to do testing of integration adapters

### ISSUE THREAD

**Issue by einari** [aksio-insurtech/Cratis#230]
With the adapter being a black box, it is hard to do automated tests/specs.
The goal it to be able to send data in the source format into it, given a certain context of events already produced and then assert that we get the correct output.

This depends on #215.

Design idea:

```csharp
public class when_name_has_changes : Specification
{
     AdapterImportContext<MyAdapter> context;

     void Establish()
     {
          context = new(new[]
          {
               new PersonRegistered("John", "Doe", "Address",....);
          });
     }

     void Because() => context.Import(new SomePerson("Johnny", "Doe"...));

     [Fact] void should_append_name_changed() => context.ShouldAppendEvents(new NameChanged("Johnny"));
}
```

## Tasks

- [x] Must be able to assert that correct events are appended on import
- [x] Must be able to give it a context of already appended events
- [x] Must be able to assert that expected state is reached for a specific instance of a model from the projection, both independently and in the context of an adapter.
- [x] Projection specs independently.
- [x] Documentation
- [x] Fix MSBuild / Directory props in Sample to work with Template as well as local development

**Comment by Torgeir-Hansen** [comment]
There are a couple of things I would like to be testable here: 
- As in your example: load up a state based on events and then apply an updated model, and then assert the event(s) generated.
- I also want to be able to inspect the projection state after injecting events (which also means I want to be able to injects events multiple times, not only via the ctor).

However, testing the projection is a more generic issue as I also want to be able to test IProjectionFor implementations.
If they both use the same code, this bit should be done generally.
For the projection testing we'll need the ability to throw events at it, and read the generated state.

```
public class address_changed : Specification
{
    SomeInMemoryDbImplementation testDb = new();
    TestProjectionBuilderFor testProjectionEngine;
    PersonRegistered _personRegisteredEvent = new(Guid.NewGuid(), "Name Namely");
    CurrentAddressUpdated _currentAddressUpdatedEvent = new("Duckburg");

    async Task Establish()
    {
        testProjectionEngine = new TestProjectionBuilderFor<PersonDetails>(testDb);
        
        // Configure the projection with definition from my projection (or adapter for that sake).
        new MyIProjectionForImplementation().DefineModel(testProjectionEngine);

        await testProjectionEngine.Handle(_personRegisteredEvent);
    }

    Task Because() => testProjectionEngine.Handle(_currentAddressUpdatedEvent);

    [Fact]
    void city_was_updated() => testDb.GetById(_personRegisteredEvent.PersonId)
        .Address.City.ShouldEqual(_currentAddressUpdatedEvent.City);
}
```
