### ISSUE TITLE
Change how we connect client to kernel

### ISSUE THREAD

**Issue by einari** [aksio-insurtech/Cratis#667]
# Background

We've been using the Orleans ClusterClient and just consuming grains in the client.
The downside of this is that there becomes a direct coupling between the client and kernel. 
In addition, we become a victim of the turn based threading model of Orleans, bleeding it to a certain extent into the client. This becomes very evident when dealing with observers and the pub/sub stream between the client and server and catching up on these streams. We basically end up getting a lot of timeouts.

## The plan

We want to change this for the first iteration into a REST API based approach. The kernel having a set of REST APIs and we just consume these in the client with nice wrappers. Secondly for observers, we want the Kernel to call the client also using REST for now. This is not the most optimal approach, but we will get to a better place first and then we can iterate on it.

Obviously we're doing this to fix a concrete bug during startup and catching up. But there are some added benefits to this:

- The client becomes decoupled from the kernel and can in fact in the future be versioned independently
- Performing tasks with the Kernel can be done using any HTTP enabled tool (cURL, PostMan)
- Enables the possibility for other client types for other languages and lowers the barrier to implement one
- Due to the decoupling, we can upgrade technologies and dependencies in the Kernel without affecting the client
- The .NET client could be targeting .NET standard 2 if we want, catching a broader variety
- .... and more.. I'm sure :)

## Tasks

- [x] Client to Kernel connectivity for single node, typically the development localhost scenario
- [ ] Static cluster registration connectivity for clustered mode, a collection of servers and a simple round-robin strategy
- [ ] Orleans - Azure Storage table clustered mode, read the table and connect to active servers, refresh and also here a round-robin strategy for now.
- [x] Create and hook up Tenant configuration API
- [x] Create and hook up Read Model configuration API per Microservice
- [x] Create and hook up Event Sequence API for appending
- [x] Create and hook up Projection registration API
- [x] Create and hook up Immediate projection API
- [x] Create and hook up Schema API
- [x] Refactor how we do observers - introduce a mechanism for subscribing with an actor
- [x] Create and hook up Observer API
- [x] Hook up Rules to Immediate projection API
- [x] Introduce a HTTP Client Observer type that subscribes to the observer
- [ ] Kernel to Client connectivity - round-robin to registered clients
- [x] Client - Kernel backchannel for tracking connected clients, observers should use this and not fail partitions if clients aren't connected. Also unsubscribe observers automatically when the client instances are all gone.
- [x] Fix Projection observer type
- [x] Fix Inbox observer type
- [x] Fix Integration to hook up correctly
- [x] Remove in-memory pub/sub
- [x] Post Client connected - similar to IPerformBootProcedure - called everytime we're connected
- [x] Change to performing tasks when client is connected (Observers, Projections, Schemas, OutboxProjections)
- [x] Make workbench work with the new client APIs
- [x] Implement inside silo client - for when the Kernel is using its own APIs
- [x] Make `DefineState` on `RuleFor` abstract - requiring it to be implemented.
- [x] Change from maintaining what connected clients we have inside the ObserverSubscriber to having a grain service that exists on every silo that we can ask.
- [x] Handle client 404 as disconnected - set observer as disconnected
- [x] Acknowledge endpoint for client. Kernel should call it to be sure the client is there when connected.
- [x] Projections keep replaying on startup - needs to be fixed
- [x] TenantConfiguration needs to hooked up
- [x] Simplify codebase by consolidating all projects in the Kernel and use namespaces instead.

## Midway refactoring tasks

- [x] Remove WebSockets
- [x] Connect endpoint should be the one we use for connecting with ClientInformation
- [x] ClientInformation should hold endpoint for a liveness probe for the Kernel to call on a timer to see if is alive
- [x] Kernel callback to Client - ping/pong for liveness
- [x] ClientObserverSubscriber - return a result
- [x] 404 from Client for observers should throw a Disconnected exception. Return result with disconnected.
- [x] Anything but 200 from Client for observers should throw a "error" exception. Return result with errored.
