### ISSUE TITLE
Refactor observers

### ISSUE THREAD

**Issue by einari** [aksio-insurtech/Cratis#722]
The goal is to refactor how the Observer is implemented.
We do this to get a better hold of what it is supposed to be doing and guarantee the quality of it and maintainability.
Today the code is convoluted and the Observer is one big class consisting of a set of different partial classes to it. 

Today it takes on the responsibility of being a statemachine, handling events, handling failed partitions and catching up.
We want to separate this into 3 different grains with clearer responsibilities and also technical benefits to the solution.

- Observer supervisor grain, handles the main statemachine and handling of "happy" path vanilla events
- Failed partition grain, handles only a specific partition and also then has the partition identifier as part of its identity
- CatchUp grain, handles only the job of catching up when an observer is behind.

## Failed partitions

The benefit of the failed partitions being its own grain is that you can then have a timer for retry that is for the partition and not one timer that handles all partitions, as the implementation is today. That means they run independently as they happen. Being only for a partition, the code gets very much simplified. Within the grain itself it also gets the benefit of potentially talking directly to the underlying eventstore rather than using the Orleans streams for the catching up of the failed partition.
Failed partition grain would inherit from the base Observer. Letting the failed partition grain leverage the underlying data store directly could also be a good idea to avoid cache misses.

Quick workflow description:

| Responsible | Description |
| ------------ | ------------ |
| Observer supervisor |  When an event is handled and it is for a failed partition we should store the event sequence number on the failed partition state. |
| Failed partitions | When the failed partition has caught up, we unsubscribe from the event stream and notify the supervisor with the event sequence number of the last event that was handled |
|Observer supervisor  | When the supervisor is being told a partition is caught up, it should check if the stored event sequence number for the failed partition is the same as the event sequence number of the last event that was handled.  If so, the partition is caught up and the failed partition state can be removed. |
| Observer supervisor | When the supervisor is being told a partition is caught up, it should check if the stored event sequence number for the failed partition is not the same as the event sequence number of the last event that was handled. f not, the partition is not caught up and the failed partition state should be updated with the event sequence number of the last event that was handled. And we start a separate grain that catches up specifically for the partition starting from the position that the failed partition reported on + 1. |

## Catching up

Catching up can be a resource intensive operation when there are a lot of events to catch up. Using the Orleans streams is not the most optimal solution to this. It would also then make sure we get a lot more cache hits with the underlying cache mechanism we have than necessary. By leveraging the data store directly and the `IEventCursor` we have, we can get events in bulk and catch up faster. Catching up would inherit from the common base Observer.

| Responsible | Description |
| ------------ | ------------ |
| Observer supervisor | When the observer is behind, we start a catch up that runs on its own grain. Sets its state to catchup. And will not start subscribing to the stream. |
| Catch up grain | Will talk directly to the event store database and read all events for the event sequence id and event types. |
| Catch up grain | Failed partitions can be scheduled till after the catch up is complete. This is to prevent the catch up from being blocked by a failed partition.  Failed partitions encountered by the CatchUp grain should be passed to the Observer supervisor for processing.|
| Catch up grain | When the catch up is complete, we notify the observer supervisor with the event sequence number of the last event that was handled and any failed partitions. |

## Base Observer type

The base observer will have the necessary logic for handling and filtering events:

- Filter method for event types
- Filter method for event types and partition
- Handle method(s)

## Tasks

- [x] Rename Observer to ObserverSupervisor
- [x] Introduce a base class for Observer
- [x] Implement Failed paritition grain
- [x] Implement Catch Up grain
- [x] Implement Failed partition state provider
- [x] Implement Catch Up grain state provider
- [x] Hook up Failed partition grain  in the ObserverSupervisor
- [x] Hook up Catch Up grain in the ObserverSupervisor
